set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

TargetDir := env_var_or_default("CARGO_TARGET_DIR", "target")

[windows]
release:
    cargo build --release
    Copy-Item -Path "{{TargetDir}}\release\gyroflow_ofx.dll" -Destination "C:\Program Files\Common Files\OFX\Plugins\GyroflowNiyien.ofx.bundle\Contents\Win64\GyroflowNiyien.ofx" -Force

[windows]
deploy:
    #!powershell
    $ErrorActionPreference = 'Stop'

    cargo build --profile deploy
    cd "{{TargetDir}}"
    Remove-Item -Recurse -Force gyroflow-niyien-ofx-windows, GyroflowNiyien-OpenFX-windows.zip -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Path "gyroflow-niyien-ofx-windows/GyroflowNiyien.ofx.bundle/Contents/Win64" -Force
    cp "deploy/gyroflow_ofx.dll" "gyroflow-niyien-ofx-windows/GyroflowNiyien.ofx.bundle/Contents/Win64/GyroflowNiyien.ofx"
    cp "{{justfile_directory()}}/res/Info.plist" "gyroflow-niyien-ofx-windows/GyroflowNiyien.ofx.bundle/Contents/"
    cp "{{justfile_directory()}}/../LICENSE" "gyroflow-niyien-ofx-windows/GyroflowNiyien.ofx.bundle/Contents/"
    cd gyroflow-niyien-ofx-windows ; 7z a ../GyroflowNiyien-OpenFX-windows.zip .

[macos]
deploy:
    #!/bin/bash
    set -e

    rustup target add aarch64-apple-darwin
    rustup target add x86_64-apple-darwin

    cargo build --profile deploy --target x86_64-apple-darwin
    cargo build --profile deploy --target aarch64-apple-darwin

    version=$(cargo pkgid | sed -E 's/.*@([^@]+)$/\1/')
    version_short=$(echo "$version" | sed -E 's/[-+].*//')

    if [[ "$GITHUB_REF" == *"tags"* ]]; then
        version="${version}.0"
        version_short="${version_short}.0"
    else
        if [[ -z "$GITHUB_RUN_NUMBER" ]]; then
            version="${version}-dev"
            version_short="${version_short}.1"
        else
            version="${version}.${GITHUB_RUN_NUMBER}"
            version_short="${version_short}.${GITHUB_RUN_NUMBER}"
        fi
    fi

    cd "{{TargetDir}}"
    rm -Rf gyroflow-niyien-ofx-macos GyroflowNiyien-OpenFX-macos.dmg
    mkdir -p gyroflow-niyien-ofx-macos/GyroflowNiyien.ofx.bundle/Contents/MacOS

    lipo {x86_64,aarch64}-apple-darwin/deploy/libgyroflow_ofx.dylib -create -output gyroflow-niyien-ofx-macos/GyroflowNiyien.ofx.bundle/Contents/MacOS/GyroflowNiyien.dylib
    cp "{{justfile_directory()}}/res/Info.plist" gyroflow-niyien-ofx-macos/GyroflowNiyien.ofx.bundle/Contents/
    cp "{{justfile_directory()}}/../LICENSE"     gyroflow-niyien-ofx-macos/GyroflowNiyien.ofx.bundle/Contents/

    /usr/libexec/PlistBuddy -c "add CFBundleVersion string $version_short" gyroflow-niyien-ofx-macos/GyroflowNiyien.ofx.bundle/Contents/Info.plist
    /usr/libexec/PlistBuddy -c "add CFBundleShortVersionString string $version" gyroflow-niyien-ofx-macos/GyroflowNiyien.ofx.bundle/Contents/Info.plist

    codesign -vvvv --strict --options=runtime --timestamp --force -s ${SIGNING_FINGERPRINT} gyroflow-niyien-ofx-macos/GyroflowNiyien.ofx.bundle/Contents/MacOS/GyroflowNiyien.dylib
    mv gyroflow-niyien-ofx-macos/GyroflowNiyien.ofx.bundle/Contents/MacOS/GyroflowNiyien.dylib gyroflow-niyien-ofx-macos/GyroflowNiyien.ofx.bundle/Contents/MacOS/GyroflowNiyien.ofx

    codesign -vvvv --deep --strict --options=runtime --timestamp --force -s ${SIGNING_FINGERPRINT} gyroflow-niyien-ofx-macos/GyroflowNiyien.ofx.bundle
    codesign -vvvv --deep --verify gyroflow-niyien-ofx-macos/GyroflowNiyien.ofx.bundle

    pushd gyroflow-niyien-ofx-macos
        zip -r ../GyroflowNiyien-OpenFX-macos.zip GyroflowNiyien.ofx.bundle
    popd

    ln -sf /Library/OFX/Plugins "gyroflow-niyien-ofx-macos/"
    hdiutil create "GyroflowNiyien-OpenFX-macos.dmg" -volname "Gyroflow(Niyien) OpenFX plugin" -fs HFS+ -srcfolder "gyroflow-niyien-ofx-macos/" -ov -format UDZO -imagekey zlib-level=9

    codesign -vvvv --strict --options=runtime --timestamp --force -s ${SIGNING_FINGERPRINT} "GyroflowNiyien-OpenFX-macos.dmg"
    codesign -vvvv --deep --verify "GyroflowNiyien-OpenFX-macos.dmg"

[linux]
deploy:
    #!/bin/bash
    set -e

    cargo build --profile deploy
    cd "{{TargetDir}}"
    rm -Rf gyroflow-niyien-ofx-linux GyroflowNiyien-OpenFX-linux.zip
    mkdir -p gyroflow-niyien-ofx-linux/GyroflowNiyien.ofx.bundle/Contents/Linux-x86-64
    cp deploy/libgyroflow_ofx.so gyroflow-niyien-ofx-linux/GyroflowNiyien.ofx.bundle/Contents/Linux-x86-64/GyroflowNiyien.ofx
    cp "{{justfile_directory()}}/res/Info.plist" gyroflow-niyien-ofx-linux/GyroflowNiyien.ofx.bundle/Contents/
    cp "{{justfile_directory()}}/../LICENSE"     gyroflow-niyien-ofx-linux/GyroflowNiyien.ofx.bundle/Contents/
    cd gyroflow-niyien-ofx-linux && zip -r ../GyroflowNiyien-OpenFX-linux.zip .
