set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

TargetDir := env_var_or_default("CARGO_TARGET_DIR", "target")
#export RUSTFLAGS := "-Zmacro-backtrace"

[windows]
release:
    cargo build --release
    Copy-Item -Force '{{TargetDir}}\release\gyroflow_adobe.dll' '{{TargetDir}}\release\GyroflowNiyien.aex'
    Start-Process PowerShell -Verb runAs -ArgumentList "-command Copy-Item -Force '{{TargetDir}}\release\gyroflow_adobe.dll' 'C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore\GyroflowNiyien-Adobe-windows.aex'"

[windows]
build:
    cargo build
    Start-Process PowerShell -Verb runAs -ArgumentList "-command Copy-Item -Force '{{TargetDir}}\debug\gyroflow_adobe.dll' 'C:\Program Files\Adobe\Common\Plug-ins\7.0\MediaCore\GyroflowNiyien-Adobe-windows.aex'"

[windows]
deploy:
    #!powershell
    $ErrorActionPreference = 'Stop'

    cargo build --profile deploy
    cd "{{TargetDir}}"
    Copy-Item -Force "deploy\gyroflow_adobe.dll" "GyroflowNiyien-Adobe-windows.aex"

[macos]
deploy:
    #!/bin/bash
    set -e

    rustup target add aarch64-apple-darwin
    rustup target add x86_64-apple-darwin

    cargo build --profile deploy --target x86_64-apple-darwin
    cargo build --profile deploy --target aarch64-apple-darwin

    version=$(grep '^version' Cargo.toml | sed -E 's/version = "(.+)".*/\1/')
    version_short=$(echo $version | sed -E 's/-.*//')

    if [[ "$GITHUB_REF" == *"tags"* ]]; then
        version="${version}.0"
        version_short="${version_short}.0"
    else
        if [[ -z "$GITHUB_RUN_NUMBER" ]]; then
            version="${version}-dev"
            version_short="${version_short}.1"
        else
            version="${version}.${GITHUB_RUN_NUMBER}"
            version_short="${version_short}.${GITHUB_RUN_NUMBER}"
        fi
    fi

    cd "{{TargetDir}}"
    rm -Rf gyroflow-niyien-adobe-macos GyroflowNiyien-Adobe-macos.dmg
    mkdir -p gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/Resources
    mkdir -p gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/MacOS

    echo "eFKTFXTC" >> gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/PkgInfo
    /usr/libexec/PlistBuddy -c 'add CFBundlePackageType string eFKT' gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/Info.plist
    /usr/libexec/PlistBuddy -c 'add CFBundleSignature string FXTC' gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/Info.plist
    /usr/libexec/PlistBuddy -c 'add CFBundleIdentifier string com.niyien.gyroflow.adobe' gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/Info.plist
    /usr/libexec/PlistBuddy -c 'add CFBundleExecutable string GyroflowNiyien' gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/Info.plist
    /usr/libexec/PlistBuddy -c "add CFBundleVersion string $version_short" gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/Info.plist
    /usr/libexec/PlistBuddy -c "add CFBundleShortVersionString string $version" gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/Info.plist

    cp x86_64-apple-darwin/deploy/gyroflow_adobe.rsrc gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/Resources/GyroflowNiyien.rsrc

    lipo {x86_64,aarch64}-apple-darwin/deploy/libgyroflow_adobe.dylib -create -output gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/MacOS/GyroflowNiyien.dylib
    mv gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/MacOS/GyroflowNiyien.dylib gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin/Contents/MacOS/GyroflowNiyien

    codesign -vvvv --deep --strict --options=runtime --timestamp --force -s ${SIGNING_FINGERPRINT} gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin
    codesign -vvvv --deep --verify gyroflow-niyien-adobe-macos/GyroflowNiyien.plugin

    pushd gyroflow-niyien-adobe-macos
        zip -r ../GyroflowNiyien-Adobe-macos.zip GyroflowNiyien.plugin
    popd

    ln -sf "/Library/Application Support/Adobe/Common/Plug-ins/7.0/MediaCore/" "gyroflow-niyien-adobe-macos/"
    hdiutil create "GyroflowNiyien-Adobe-macos.dmg" -volname "Gyroflow(Niyien) Adobe plugin" -fs HFS+ -srcfolder "gyroflow-niyien-adobe-macos/" -ov -format UDZO -imagekey zlib-level=9

    codesign -vvvv --strict --options=runtime --timestamp --force -s ${SIGNING_FINGERPRINT} "GyroflowNiyien-Adobe-macos.dmg"
    codesign -vvvv --deep --verify "GyroflowNiyien-Adobe-macos.dmg"

[linux]
deploy:
    # No Adobe for linux
